### ISSUE TITLE
Not update the view if model didn't change

### ISSUE THREAD

**Issue by Thecentury** [AvaloniaCommunity/Avalonia.FuncUI#101]
Hi @JaggerJo!

What do you think about the idea of not generating the new view and not patching the UI when model hasn't changed after the update function? 

Sometimes it is quite tedious to create comparers for all FuncUI properties to eliminate the need to patch the value in the UI, and this change can help to fix problems when repeated setting of the same property with the same value nevertheless changes something under the hood.

**Comment by JaggerJo** [comment]
Hi @Thecentury ,

yeah makes sense. I think this should be done / configured via Elmish ?

**Comment by Thecentury** [comment]
@JaggerJo 

It can be done like this:

```fsharp
let withHost' (host : IViewHost) (program : Program<'arg, 'model, 'msg, #IView>) =
    let syncDispatch (dispatch : Dispatch<'msg>) : Dispatch<'msg> = ...

    let stateRef = ref None
    let setState state dispatch =
        // create new view and update the host only if new model is not equal to a prev one
        let stateDiffers = (Some state).Equals(!stateRef) |> not
        if stateDiffers then
            stateRef := Some state
            let view = ((Program.view program) state dispatch)
            host.Update (Some (view :> IView))

    program
    |> Program.withSetState setState
    |> Program.withSyncDispatch syncDispatch
```

**Comment by JaggerJo** [comment]
can you take a look at #106 ?

**Comment by Thecentury** [comment]
@JaggerJo Looks good.
