### ISSUE TITLE
Support for NativeMenu

### ISSUE THREAD

**Issue by JonCanning** [AvaloniaCommunity/Avalonia.FuncUI#113]
I'd like to be able to set the NativeMenu like this:

https://github.com/AvaloniaUI/Avalonia/issues/3541#issuecomment-583905588

**Comment by JaggerJo** [comment]
Hey @JonCanning ,

thanks for the patience. There is currently no DSL for Native Menus. BUT, it's simple to use them with plain F#. Here is a small sample extending the **CounterApp** with a native menu!

If you haven't done this already set the `Application.Name` Property.

```fsharp
type App() =
    
    inherit Application()

    override this.Initialize() =
        this.Styles.Load "resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"
        this.Styles.Load "resm:Avalonia.Themes.Default.Accents.BaseDark.xaml?assembly=Avalonia.Themes.Default"

        // 🚩name visible in native menu
        this.Name <- "Counter App"
```

```fsharp
type MainWindow() as this =
    inherit HostWindow()
    do
        base.Title <- "Counter Example"
        base.Height <- 400.0
        base.Width <- 400.0    

        // 🚩create menu and menu items
        let incrementItem = NativeMenuItem "Increment"
        let decrementItem = NativeMenuItem "Decrement"
        
        let editCounterItem = NativeMenuItem "Edit Counter"
        let editCounterMenu =  NativeMenu()
        editCounterItem.Menu <- editCounterMenu
        editCounterMenu.Add incrementItem
        editCounterMenu.Add decrementItem
        
        let nativeMenu = NativeMenu()
        nativeMenu.Add editCounterItem
        
        // 🚩set menu
        NativeMenu.SetMenu(this, nativeMenu)
        
        // 🚩hook menu actions in Elmish
        let menuSub (_state: Counter.State) =
            let sub (dispatch: Counter.Msg -> unit) =
                incrementItem.Clicked.Add (fun _ -> dispatch Counter.Msg.Increment)
                decrementItem.Clicked.Add (fun _ -> dispatch Counter.Msg.Decrement)
                ()
                        
            Cmd.ofSub sub
                    
        Elmish.Program.mkSimple (fun () -> Counter.init) Counter.update Counter.view
        |> Program.withHost this
        // 🚩 use menu subscription
        |> Program.withSubscription menuSub
        |> Program.withConsoleTrace
        |> Program.run
```

hope this helps 😉

**Comment by wuzlai** [comment]
> ```fsharp
> ```fsharp
> type App() =
>     
>     inherit Application()
> 
>     override this.Initialize() =
>         this.Styles.Load "resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"
>         this.Styles.Load "resm:Avalonia.Themes.Default.Accents.BaseDark.xaml?assembly=Avalonia.Themes.Default"
> 
>         // 🚩name visible in native menu
>         this.Name <- "Counter App"
> ```
> 
> 
> ```fsharp
> type MainWindow() as this =
>     inherit HostWindow()
>     do
>         base.Title <- "Counter Example"
>         base.Height <- 400.0
>         base.Width <- 400.0    
> 
>         // 🚩create menu and menu items
>         let incrementItem = NativeMenuItem "Increment"
>         let decrementItem = NativeMenuItem "Decrement"
>         
>         let editCounterItem = NativeMenuItem "Edit Counter"
>         let editCounterMenu =  NativeMenu()
>         editCounterItem.Menu <- editCounterMenu
>         editCounterMenu.Add incrementItem
>         editCounterMenu.Add decrementItem
>         
>         let nativeMenu = NativeMenu()
>         nativeMenu.Add editCounterItem
>         
>         // 🚩set menu
>         NativeMenu.SetMenu(this, nativeMenu)
>         
>         // 🚩hook menu actions in Elmish
>         let menuSub (_state: Counter.State) =
>             let sub (dispatch: Counter.Msg -> unit) =
>                 incrementItem.Clicked.Add (fun _ -> dispatch Counter.Msg.Increment)
>                 decrementItem.Clicked.Add (fun _ -> dispatch Counter.Msg.Decrement)
>                 ()
>                         
>             Cmd.ofSub sub
>                     
>         Elmish.Program.mkSimple (fun () -> Counter.init) Counter.update Counter.view
>         |> Program.withHost this
>         // 🚩 use menu subscription
>         |> Program.withSubscription menuSub
>         |> Program.withConsoleTrace
>         |> Program.run
> ```
> ```

Hi，I aslo want to modify the menu name.but i do not know your code. could you tell me how to operate it ??

**Comment by JaggerJo** [comment]
> Hi，I aslo want to modify the menu name.but i do not know your code. could you tell me how to operate it ??

What exactly do you mean by menu name ?

**Comment by FoggyFinder** [comment]
> What exactly do you mean by menu name ?

Title:

![Title](https://files.gitter.im/547b1838db8155e6700d97d7/nF13/image.png)

Image is taken from gitter

**Comment by JaggerJo** [comment]
> > What exactly do you mean by menu name ?
> 
> Title:
> 
> ![Title](https://camo.githubusercontent.com/9a56d4a7b5026a135240a63a33c62160a7baf457/68747470733a2f2f66696c65732e6769747465722e696d2f3534376231383338646238313535653637303064393764372f6e4631332f696d6167652e706e67)
> 
> Image is taken from gitter

Ahh, I see. Thats actually in my sample:

```fsharp

type App() =
    
    inherit Application()

    override this.Initialize() =
        this.Styles.Load "resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"
        this.Styles.Load "resm:Avalonia.Themes.Default.Accents.BaseDark.xaml?assembly=Avalonia.Themes.Default"

        // 🚩name visible in native menu
        this.Name <- "Counter App"
```

**Comment by wuzlai** [comment]
> > > What exactly do you mean by menu name ?
> > 
> > 
> > Title:
> > ![Title](https://camo.githubusercontent.com/9a56d4a7b5026a135240a63a33c62160a7baf457/68747470733a2f2f66696c65732e6769747465722e696d2f3534376231383338646238313535653637303064393764372f6e4631332f696d6167652e706e67)
> > Image is taken from gitter
> 
> Ahh, I see. Thats actually in my sample:
> 
> ```fsharp
> type App() =
>     
>     inherit Application()
> 
>     override this.Initialize() =
>         this.Styles.Load "resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"
>         this.Styles.Load "resm:Avalonia.Themes.Default.Accents.BaseDark.xaml?assembly=Avalonia.Themes.Default"
> 
>         // 🚩name visible in native menu
>         this.Name <- "Counter App"
> ```

Well,thanks,but my problem are three,1st is how to modify  the app menu header on osx,just like the picture you see.
2rd is how to replace all drop-down box options.3th is Which file should I write the code you provided in? i guess you can get my idea.

**Comment by wuzlai** [comment]
> > > What exactly do you mean by menu name ?
> > 
> > 
> > Title:
> > ![Title](https://camo.githubusercontent.com/9a56d4a7b5026a135240a63a33c62160a7baf457/68747470733a2f2f66696c65732e6769747465722e696d2f3534376231383338646238313535653637303064393764372f6e4631332f696d6167652e706e67)
> > Image is taken from gitter
> 
> Ahh, I see. Thats actually in my sample:
> 
> ```fsharp
> type App() =
>     
>     inherit Application()
> 
>     override this.Initialize() =
>         this.Styles.Load "resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"
>         this.Styles.Load "resm:Avalonia.Themes.Default.Accents.BaseDark.xaml?assembly=Avalonia.Themes.Default"
> 
>         // 🚩name visible in native menu
>         this.Name <- "Counter App"
> ```

thank you ,Paste the picture for me

**Comment by wuzlai** [comment]
> > > > What exactly do you mean by menu name ?
> > > 
> > > 
> > > Title:
> > > ![Title](https://camo.githubusercontent.com/9a56d4a7b5026a135240a63a33c62160a7baf457/68747470733a2f2f66696c65732e6769747465722e696d2f3534376231383338646238313535653637303064393764372f6e4631332f696d6167652e706e67)
> > > Image is taken from gitter
> > 
> > 
> > Ahh, I see. Thats actually in my sample:
> > ```fsharp
> > type App() =
> >     
> >     inherit Application()
> > 
> >     override this.Initialize() =
> >         this.Styles.Load "resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"
> >         this.Styles.Load "resm:Avalonia.Themes.Default.Accents.BaseDark.xaml?assembly=Avalonia.Themes.Default"
> > 
> >         // 🚩name visible in native menu
> >         this.Name <- "Counter App"
> > ```
> 
> Well,thanks,but my problem are three,1st is how to modify the app menu header on osx,just like the picture you see.
> 2rd is how to replace all drop-down box options.3th is Which file should I write the code you provided in? i guess you can get my idea.

I got a tip from gitter.Now,the first problem is ok, can you tell me the rest problems.
i attch the first answer.
change that by setting the application name...in App.xaml
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:XamlControlsGallery"
             x:Class="XamlControlsGallery.App" Name="NewBrand10.5">


![image](https://user-images.githubusercontent.com/7692353/92340292-4c396780-f0ec-11ea-9772-e452b57df5f7.png)

**Comment by wuzlai** [comment]
> > > What exactly do you mean by menu name ?
> > 
> > 
> > Title:
> > ![Title](https://camo.githubusercontent.com/9a56d4a7b5026a135240a63a33c62160a7baf457/68747470733a2f2f66696c65732e6769747465722e696d2f3534376231383338646238313535653637303064393764372f6e4631332f696d6167652e706e67)
> > Image is taken from gitter
> 
> Ahh, I see. Thats actually in my sample:
> 
> ```fsharp
> type App() =
>     
>     inherit Application()
> 
>     override this.Initialize() =
>         this.Styles.Load "resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"
>         this.Styles.Load "resm:Avalonia.Themes.Default.Accents.BaseDark.xaml?assembly=Avalonia.Themes.Default"
> 
>         // 🚩name visible in native menu
>         this.Name <- "Counter App"
> ```

en .i use another way to solve it,i attach the code.
only add code in app.xml can replace the menu, thank you i have no problems
![image](https://user-images.githubusercontent.com/7692353/92344468-1fd81800-f0f9-11ea-9db3-2b027e707cdd.png)
