### ISSUE TITLE
html docs ?

### ISSUE THREAD

**Issue by dsyme** [AvaloniaCommunity/Avalonia.FuncUI#114]
Hi @JaggerJo are the HTML docs for this project published anywhere?

I'm adding a "Use F# for Desktop Apps" to http://fsharp.org and making this a main entry, just wondering what to link to.

**Comment by AngelMunoz** [comment]
Hi, @Jaggerjo has been busy these days but we were working on HTML docs the last weeks actually it's still lacking content but I think overall it should work for "Getting Started"
we might move the docs to its own repository and activate GitHub pages there just give us a few days to sort that out

**Comment by JaggerJo** [comment]
Hey @dsyme ,

as @AngelMunoz already mentioned we're currently in the middle of setting up proper Documentation for FuncUI (now at https://github.com/AvaloniaCommunity/Avalonia.FuncUI.Docs).

I've seen you linked to the main repo, so if we think the Docs are ready we can just link to them in the readme.

Thanks for mentioning FuncUI on [fsharp.org](https://fsharp.org/use/desktop-apps/)!
