### ISSUE TITLE
Add link to docs to the ReadMe

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaCommunity/Avalonia.FuncUI#117]
I think it makes sense to add link to the docs (or alternatively replace one that leads to the wiki) in the ReadMe under `Getting started` section.

**Comment by AngelMunoz** [comment]
The reason (most likely) that we haven't done so is that we still lack a lot of controls from the documentation but I do agree that it makes sense since the getting started guides are kind of already in place
cc @JaggerJo

**Comment by JaggerJo** [comment]
@AngelMunoz I think the Docs are already a lot better than what we have in the Wiki. If we link to the Docs we should delete the Wiki / point to the docs there too 🙂 (because fsharp.org points to the wiki I think)

**Comment by JaggerJo** [comment]
added a link to the Documentation.
