### ISSUE TITLE
Grid doesn't work properly

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaCommunity/Avalonia.FuncUI#122]
MCVE

```fs
module Sample =
    open Avalonia.Controls

    [<RequireQualifiedAccess>]
    type State = 
        | First
        | Second

    let update state _ = state
    let init() = State.First

    let first dispatch = 
        Grid.create [
            Grid.rowDefinitions "Auto"
            Grid.columnDefinitions "Auto"
            Grid.children [
                Button.create [
                    Grid.column 0
                    Grid.row 0 
                    Button.content "Second"
                    Button.onClick (fun _ -> State.Second |> dispatch)
                ]
            ]
        ]

    let second dispatch =
        Grid.create [
            Grid.rowDefinitions "Auto"
            Grid.children [
               Button.create [
                   Grid.row 0
                   Button.content "First"
                   Button.onClick (fun _ -> State.First |> dispatch)
               ]
            ]
        ]   

    let view (state: State) (dispatch) =
        match state with
        | State.First -> first dispatch :> IView
        | State.Second -> second dispatch :> IView
```

```fs
Elmish.Program.mkSimple Sample.init Sample.update Sample.view
```

**_Expected behaviour:_**

Click on btn navigates to next page

![1](https://user-images.githubusercontent.com/16510738/83259259-647e1a00-a1c0-11ea-8db0-e321424b974d.gif)

**_Actual behaviour:_**

![2](https://user-images.githubusercontent.com/16510738/83259282-6cd65500-a1c0-11ea-973c-4223f3ab2b95.gif)

Click on button changes state but view looks the same.

Without specifying`Grid.columnDefinitions "Auto"` and `Grid.column 0` for the first view it works fine.

I don't like title but I wasn't able to come to anything better.

**Comment by JaggerJo** [comment]
Hey @FoggyFinder 

thanks for the great reproduction example.

When navigating from first to second the columnDefinitions property is not specified. This means FuncUI tries to reset the value, in this case it tried to reset it to null. This is not a valid value in Avalonia, so avalonia throws an exception.

https://github.com/AvaloniaUI/Avalonia/blob/ee6e49def6792b35c0b305251484f2a2c94b7d82/src/Avalonia.Controls/Grid.cs#L202

Luckily FuncUI supports those edge cases, it just has to be specified in the DSL. Added that in the following commit, and it works.

https://github.com/AvaloniaCommunity/Avalonia.FuncUI/commit/328bbc79951f7612b8eb124538aa1a347ae090cb

Will publish an updated version right away :)

**Comment by JaggerJo** [comment]
https://www.nuget.org/packages/JaggerJo.Avalonia.FuncUI.DSL/0.4.1 might take a while until its listed
