### ISSUE TITLE
Adding children/child to a button?

### ISSUE THREAD

**Issue by smolck** [AvaloniaCommunity/Avalonia.FuncUI#124]
Is it possible to add children or a single child to a button? For example to create buttons like those in the sidebar of this app:
![image](https://raw.githubusercontent.com/klaussinani/ao/master/docs/media/list-navigation.gif)

So, ideally I'd do something like this:
```fsharp
Button.create [
    Button.child [
        StackPanel.create [ (* ... *) ]
    ]
    Button.fontSize 20.0
    // ...
]
```
Is that possible or is there another way to achieve this sort of thing?

**Comment by AngelMunoz** [comment]
for that, you would need to use the `content` property

```fsharp

let btncontent = 
    StackPanel.create [ (* ... content ... *) ]

Button.create [
    Button.content btncontent
]
```

**Comment by smolck** [comment]
Thanks a lot! That works!

However, I'm still having trouble getting the `TextBlock`s within the `StackPanel` to align correctly.  What ends up happening is the two `TextBlock`s go right next to each other, so they appear as one. Instead, I'd like to have one `TextBlock` be aligned to the left side of the `StackPanel` and the other aligned to the right side of the `StackPanel`, like in the image I put in the original comment. Do you know how I can achieve that?

**Comment by AngelMunoz** [comment]
I think you could use `DockPanel` in that case but I'm not entirely sure

```fsharp
DockPanel.create [
  DockPanel.children [
    TextBox.create [ TextBox.dock Dock.Left ]
    TextBox.create [ TextBox.dock Dock.Right ]
  ]
]
```

or also use the HorizontalAlignment properties 
http://avaloniaui.net/docs/layout/alignment-margins-padding

**Comment by smolck** [comment]
@AngelMunoz Thanks! I went for `HorizontalAlignment`, and it works well after a few tweaks to the code. My solution was to (1) change the `StackPanel` to a `Grid`, and (2) I needed to make the `Grid`'s width equal to that of the button, otherwise the text wouldn't span the whole button. So I ended up with something like this for `Button.content`:

```fsharp
(Grid.create
    [ Grid.width (* width of button goes here *)
      Grid.children
          [ TextBlock.create
              [ TextBlock.text "text"
                TextBlock.fontSize 20.0
                TextBlock.horizontalAlignment HorizontalAlignment.Left ]
            TextBlock.create
                [ TextBlock.horizontalAlignment HorizontalAlignment.Right
                  TextBlock.text "2"
                  TextBlock.fontSize 20.0 ] ] ])
```

If you don't mind, I've got just one last question, and I figure it's better to ask it here than open a whole other issue when it's pretty small. Is there a way to set, for example, a `Grid`s width to be that of its parent? In other words, is there a way to get a child expand to fill it's parent?

**Comment by AngelMunoz** [comment]
That I wouldn't know actually.
I could guess that you can play with the Grid's Column/Row Definitions but I'm not entirely sure

you can ask in the [Gitter](https://gitter.im/Avalonia-FuncUI/community) channel to see if someone has an answer to that

**Comment by smolck** [comment]
Okay, thanks for all your help! And I didn't know about the Gitter channel! I might ask on there, but it's not really necessary in this case since I set the button's width manually and can use the same value for the Grid's width. I was just wondering if there was a more idiomatic/elegant way of doing that.

**Comment by FoggyFinder** [comment]
@smolck you can use `ItemsControl`/`ListBox` for that case and change right panel depending on click / selection

Also, for `Grid` you could use instead

```fs
Grid.columnDefinitions "Auto,*, Auto"
```

**Comment by JaggerJo** [comment]
@smolck Using HorizontalAlignment = Stretch should work when a control doesn’t fill the available space by default.

(most panels fill the available space by default if you don't set other constraints)

There is a good section about this in the docs.

https://avaloniaui.net/docs/layout/alignment-margins-padding
