### ISSUE TITLE
SelectedItem doesn't show value sometimes

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaCommunity/Avalonia.FuncUI#126]
In my app I saw something that looks rather odd: the selected item is showed only on second click. I tried to create MCVE and notice that behaviour is different depending on State.

I can't exclude that I'm missing something obvious though.

Anyway, here is a MCVE:

```fsharp
open Avalonia.Controls
open Avalonia.FuncUI.DSL
open Avalonia.FuncUI.Components
open Avalonia.Layout

module Sample =
    type State(v) =
        member __.Value = v
        override s.ToString() = s.Value.ToString()

    let init() = State(1)
    type Msg = 
        | Select of int

    let update msg _ : State =
        match msg with
        | Msg.Select v -> State(v)

    let data = [ 1..10 ] |> List.map State
    let dataTemplate (v:State) = 
        TextBlock.create [
            v.Value |> string |> TextBlock.text
        ]

    let view (state: State) (dispatch) =
        StackPanel.create [
            StackPanel.verticalAlignment VerticalAlignment.Center
            StackPanel.children [
                ComboBox.create [
                    ComboBox.dataItems data
                    ComboBox.minWidth 120.0
                    ComboBox.minHeight 50.0
                    ComboBox.selectedItem state
                    ComboBox.onSelectedItemChanged (fun v ->
                        if v <> null then
                            v
                            |> unbox<State>
                            |> fun state -> state.Value
                            |> Msg.Select
                            |> dispatch
                    )

                    ComboBox.itemTemplate 
                        (DataTemplateView<State>.create dataTemplate)
                ]
            ]
        ]
```

**Comment by JaggerJo** [comment]
Hey @FoggyFinder !

Just tried you sample and I have to admit that something strange is going on here! Interestingly I had a different issue than you describe, for me the `ComboBox` never displayed it's selected value (not even initially).

Somehow it works when your `State` class in replaced with a record `type State = { Value: int }`, but I can't really explain why.

While debugging I also noticed that it looks like the right value is set on the control, which makes it even stranger. 

Looks like it's a bug in Avalonia itself, as the example below leads to an empty combo box.

<img width="325" alt="image" src="https://user-images.githubusercontent.com/13090415/86170501-83ebc800-bb1b-11ea-9a02-d619d91fd72a.png">

```fsharp
type State(number: int) =
    member this.Value = number
    override this.ToString() = this.Value.ToString()
        
type MainWindow() =
    inherit Window()
    do
        let cb = ComboBox()
        cb.Items <- [ 1..10 ] |> List.map State
        cb.SelectedItem <- (5)
        
        base.Content <- cb
```

**Comment by FoggyFinder** [comment]
>Interestingly I had a different issue than you describe, for me the ComboBox never displayed it's selected value (not even initially).

I have the same output for MCVE (never displayed), I've described what I have in real app. I just wasn't able to create a small sample that match my case. Sorry for that. Though I think the root is the same.Well, if not I'll open another issue

> Looks like it's a bug in Avalonia itself, as the example below leads to an empty combo box.

Wonderful. Then no surprise I wasn't able to understand what's wrong with FuncUi :-)
I'll try to investigate it there.

**Comment by JaggerJo** [comment]
@FoggyFinder edited my comment above, not sure if you got notified

**Comment by FoggyFinder** [comment]
Thank you - after reading your comment I checked my code again and find the reason.

Selected item had a different type than one from collection that is bounded to `ComboBox.dataItems` (the same name but from different namespace). With all these boxing/unboxing it's easy to miss the mistake :(

Though I still unsure why item was selected correctly on a second click.

Anyway now it works as expected and I've add additional annotations to make sure everything is right. I'll be careful next time.
