### ISSUE TITLE
Update with async function

### ISSUE THREAD

**Issue by festim-deari** [AvaloniaCommunity/Avalonia.FuncUI#132]
I am building an application with Avalonia FuncUI, but can run functions with heavy computations and http requests only synchronously, i.e. blocking the main(UI) thread. Could someone please show me a way how to update with a function that runs async and returns the new state on e.g. Button.onClick?

**Comment by JaggerJo** [comment]
@festim-deari usually you use a Command for long running Actions. Take a look at [this chapter](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/commands/) in the Elmish book. (It uses a different UI framework but the essential concept is the same)

**Comment by festim-deari** [comment]
@JaggerJo Thank you. Will look into it.

**Comment by festim-deari** [comment]
> @festim-deari usually you use a Command for long running Actions. Take a look at [this chapter](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/commands/) in the Elmish book. (It uses a different UI framework but the essential concept is the same)

Got it working. Thank you!
