### ISSUE TITLE
Question: How to setup value in initialization

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaCommunity/Avalonia.FuncUI#137]
Wanna setup value with async after initialization, but don't find any examples.
https://github.com/CreateLab/WeatherUI/blob/master/WeatherUI/WeatherWindow.fs#L44

**Comment by AngelMunoz** [comment]
Made a PR to your project and left a brief explanation in the form of code comments, let me know if something else that comes up
https://github.com/CreateLab/WeatherUI/pull/1

**Comment by CreateLab** [comment]
I have one more question
How to combine commands?

**Comment by AngelMunoz** [comment]
@CreateLab  in the case of combining commands you can use `Cmd.batch [ cmd1; cmd2; cmd3; cmd4 ..... cmdn]`
let's say you have two functions that retrieve your values (similar to what you already have in your project)
```fsharp
let asyncCmd (url: string) : Cmd<SetTodos> = async {...} |> Cmd.ofAsync.result
let getText () : Cmd<Text> = 
    let text = ...  
    Cmd.ofMsg (Text text)
```

in your init function (or your update function works too) you only need to return a batch of commands

```fsharp
let init = 
    // like this
    { text = ""; todos = [] }, Cmd.batch [asyncCmd "url"; getText()];

let update msg state = 
    match msg with 
    // or like this
    | SomeMsg -> 
       let text = ...
        // you can use any Msg you need to, async or sync  Elmish will handle that for you
        state, Cmd.batch [ Cmd.ofMsg (Text text); Cmd.ofMsg (SetEnabled false)]
```

also, check this post where one of the Elmish maintainers explain a few tips about using Elmish
https://medium.com/@MangelMaxime/my-tips-for-working-with-elmish-ab8d193d52fd

**Comment by AngelMunoz** [comment]
I'll close this now but feel free to reach again if needed

**Comment by CreateLab** [comment]
ty
