### ISSUE TITLE
Can we use XAML + F# in some way?

### ISSUE THREAD

**Issue by artfuldev** [AvaloniaCommunity/Avalonia.FuncUI#142]
I'm trying to see if for declarative views, I can use XAML somehow, and use F# only as a code-behind. I just looked at this project today so I'm not familiar with the ecosystem, and was wondering if there is any way to get functional F# code with XAML-based declarative UI (as opposed to F# based)

**Comment by AngelMunoz** [comment]
With Avalonia.FuncUI not really
But you can use Avalonia with F# as if you were doing C#
> https://github.com/yatli/fvim

that project is made with Avalonia but it doesn't use Avalonia.FuncUI

the relevant fsproj code is this
https://github.com/yatli/fvim/blob/master/fvim.fsproj#L55-L67
```xml
<ItemGroup>
    <Compile Update="**\*.xaml.fs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <AvaloniaResource Include="Assets\**\*" />
    <Content Include="**\*.xaml" />
    <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
    <EmbeddedResource Include="Fonts\nerd.ttf" />
    <Content Include="Assets\*" />
    <None Include="icons\*.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
```

![image](https://user-images.githubusercontent.com/8684875/99138018-e9cc7e00-25ea-11eb-9962-55dc3f6b98d7.png)
