### ISSUE TITLE
Multiple Windows

### ISSUE THREAD

**Issue by keldor314** [AvaloniaCommunity/Avalonia.FuncUI#143]
It occurred to me - why isn't there some sort of level in the UI tree above Window?  This would make synchronizing multiple windows a lot less trouble.  Something like

```
App [
    Window [ ]
    Window [ ]
    ...
]
```

Alternately, the App level would have a single child which would be some collection of Windows.  It might also make sense to instead of App call the root Context, since maybe there's a reason why the developer would want more than one of them.

My use case is that I want a UI that's friendly with multiple monitors.  Something like Visual Studio's dock system seems like a good place to start, and it would be nice to be able to easily break toolbars and such off into separate windows without having to mess with juggling state between multiple models and update paths.

Are there limitations in Avalonia itself which would make this annoying to implement?  Maybe things to do with threading?

**Comment by JaggerJo** [comment]
Hey @keldor314 ,

thanks for the patience. That's a great question, let me get into the details a bit.

> It occurred to me - why isn't there some sort of level in the UI tree above Window? This would make synchronizing multiple windows a lot less trouble. Something like
> 
> ```
> App [
>     Window [ ]
>     Window [ ]
>     ...
> ]
> ```

There are a few thing worth considering that lead to my decision of rooting the MVU App on the window level.

```fsharp
App [
    Window [ ]
    if x then Window [ ]  
    if y then Window [ ] 
    Window [ ] 
]
```

The example above could lead to serious performance issues as adding a window in between would effectively recreate and render all windows below.

It also means we do a lot more work on every view update as we end calculating the diff for all windows.
We would need some concept of a keyed list (interesting for other cases as well) to make this more efficient.

> Alternately, the App level would have a single child which would be some collection of Windows. It might also make sense to instead of App call the root Context, since maybe there's a reason why the developer would want more than one of them.

It's a bit more complicated even as windows only exist on the desktop and avalonia is heading towards mobile support. 

> My use case is that I want a UI that's friendly with multiple monitors. Something like Visual Studio's dock system seems like a good place to start, and it would be nice to be able to easily break toolbars and such off into separate windows without having to mess with juggling state between multiple models and update paths.

Understood. I think for your scenario you might want to split the app into smaller components that then communicate with a central dispatch loop. FuncUI does not have good support for components yet, but it should be possible to create that yourself.

> Are there limitations in Avalonia itself which would make this annoying to implement? 
There might - It has been a while since I looked at it. Not sure if a window inherits from control - that's currently required for diffing. (But we could change that as it's an artificial constraint - there even is a draft PR for that)

> Maybe things to do with threading?
Hmm, I don't think threading is an issue here.

**Comment by keldor314** [comment]
Hrmm...  Let's see if I can clarify my requirements.

I'm actually coding a fractal editor, where the toolbars control parameters of the fractal.  These are flame fractals, and have a huge number of various parameters controlling different aspects of the rendering, so there are multiple tool components, to edit the coloration, the parameters for the IFS, animation, etc.  However, everything ultimately is bound to the same model, or at the very least, subsets of this model.

So I guess what I want is for the view to be virtualized, where the root can be as broad or narrow as needed, whether we're talking about a high level view spanning multiple windows or confined to the content of a panel somewhere.

Another option is to allow a view to be bound to multiple models.  For instance, it might have an internal state, but also drive a live preview through a shared external model, and ultimately commit changes to the global document model when the user hits "apply".  This also requires that a model be bound to multiple views.  And of course, the bindings need to be dynamic, where an entirely new view might be created when the user opens a dialog, etc.

Concerning mobile, I don't really see a problem.  The highest level context is simply restricted to having a single "window" control.  It's not a good idea to try to reuse a GUI between desktop and mobile anyway since the form factor is so different.

**Comment by AngelMunoz** [comment]
I can't speak for the internals but for the time being, I'll share my experience with that

I experimented with multiple windows a few months ago, but it's kind of clunky what I did was the following
- Create a class which has a CLR Event
- Subscribe to that event from my multiple windows (the windows are created from the main one)
- Provide the an interface to your update function that can call a service
```fsharp
let update  (msg : Msg) (state: State) (windowService: IMyWindowService) = 
       match msg with 
       |  OpenWindow ->
            state, Cmd.ofAsync.perform dialogService.OpenWindow ()
```
each window will have it's own Elmish loop so you can subscribe to your service's events

not sure if that helps

**Comment by AngelMunoz** [comment]
the windows would look like this on the constructor
https://github.com/AvaloniaCommunity/Avalonia.FuncUI/blob/master/src/Examples/Examples.MusicPlayer/Shell.fs#L201-L212

**Comment by AngelMunoz** [comment]
@keldor314 I have a sample for you that might work
https://github.com/AngelMunoz/MultiWindow
in that example I open each window as a `Dialog` but you can *new* the windows and show them/hide them based on the commands/subscriptions you may have based on that sample

I don't think (given the nature of Avalonia itself, Avalonia doesn't have a window tree either AFAIK) this is something possible for the moment

Please check the sample if you're interested in this and let me know if there are some questions to that approach I'll close this in the meanwhile
