### ISSUE TITLE
Wrong type on ListBox Adaptative mode attribute

### ISSUE THREAD

**Issue by rafaelhrsantos** [AvaloniaCommunity/Avalonia.FuncUI#60]
I noticed a bug on ListBox types.
ListBox.virtualizationMode is returning a ComboBox attribute instead of ListBox.

![image](https://user-images.githubusercontent.com/3744405/73107618-2b722800-3ef6-11ea-8a60-0a315319fab1.png)

**Comment by JaggerJo** [comment]
Thanks for the report. Will release a new Version with a few small fixes this week
