### ISSUE TITLE
improve Wiki

### ISSUE THREAD

**Issue by JaggerJo** [AvaloniaCommunity/Avalonia.FuncUI#64]
The Wiki currently contains a few articles that need to be reviewed. Code Examples are for FuncUI  0.1 and therefor don't work anymore (breaking change from 0.1 -> current).

**Comment by AngelMunoz** [comment]
I gave it a shot and updated/added 
- [Home](https://github.com/AvaloniaCommunity/Avalonia.FuncUI/wiki)
- [Views and Attributes](https://github.com/AvaloniaCommunity/Avalonia.FuncUI/wiki/Views-and-Attributes)
- [Basic Template](https://github.com/AvaloniaCommunity/Avalonia.FuncUI/wiki/Basic-Template)
- [Full Template](https://github.com/AvaloniaCommunity/Avalonia.FuncUI/wiki/Full-Template)

I'll try to update the Quickstart Template page also  this week
if you have feedback on them please let me know

**Comment by AngelMunoz** [comment]
Added also a unit testing doc
[Unit Testing Avalonia FuncUI Apps
](https://github.com/AvaloniaCommunity/Avalonia.FuncUI/wiki/Unit-Testing-Avalonia-FuncUI-Apps)
