### ISSUE TITLE
Failure in patching when Styles or Classes are not set

### ISSUE THREAD

**Issue by Thecentury** [AvaloniaCommunity/Avalonia.FuncUI#66]
Here is the repro: https://github.com/Thecentury/Avalonia.FuncUI.Repro

Can FuncUI provide some special handling for a set of known properties that do not allow null values to be set?

**Comment by JaggerJo** [comment]
Thanks for the great reproduction repository. 

> Can FuncUI provide some special handling for a set of known properties that do not allow null values to be set?

Thats currently not supported. 

Avalonias `StyledProperty`, `AttachedPropertiy` and `DirectProperty` all have default values. So if the `Styles` Property would be a `DirectProperty` it would just work.

```fsharp
        static member styles<'t when 't :> StyledElement>(value: Styles) : IAttr<'t> =
            let getter : ('t -> Styles) = (fun control -> control.Styles)
            let setter : ('t * Styles -> unit) = (fun (control, value) -> control.Styles <- value)
            
            AttrBuilder<'t>.CreateProperty<Styles>("Styles", value, ValueSome getter, ValueSome setter, ValueNone)
```

Adding that functionality would be fairly simple, we could just add another field to the `Property` record type [link](https://github.com/AvaloniaCommunity/Avalonia.FuncUI/blob/master/src/Avalonia.FuncUI/Types.fs#L32) and check if there is a custom default value when patching.

```fsharp
    type Property =
        {
            accessor: Accessor
            value: obj
            defaultValue: obj voption // added
            comparer: (obj * obj -> bool) voption
        }
```

The patcher needs to check if a custom default value is provided

https://github.com/AvaloniaCommunity/Avalonia.FuncUI/blob/c06d09683d0c78349c017e02963ee3ae918d806b/src/Avalonia.FuncUI/VirtualDom/VirtualDom.Patcher.fs#L52

https://github.com/AvaloniaCommunity/Avalonia.FuncUI/blob/c06d09683d0c78349c017e02963ee3ae918d806b/src/Avalonia.FuncUI/VirtualDom/VirtualDom.Patcher.fs#L64

The Attribute Builder then also should provide appropriate overloads

https://github.com/AvaloniaCommunity/Avalonia.FuncUI/blob/c06d09683d0c78349c017e02963ee3ae918d806b/src/Avalonia.FuncUI/Builder.fs#L50

Do you think that would be a good solution ?

IMHO it would be better if Avalonia would provide said Properties as `DirectProperties`.

What do you think ?

**Comment by JaggerJo** [comment]
After I thought about this a bit more I think we should include a way to do this. Not every library will do it right by default.

**Comment by Thecentury** [comment]
I'm started to work on fixing this issue.

@JaggerJo Do you think FuncUI should provide default value for avalonia properties as well? Usually they have their own default value, and as for me, just clearing them would be enough.

**Comment by JaggerJo** [comment]
> I'm started to work on fixing this issue.

nice!

> @JaggerJo Do you think FuncUI should provide default value for avalonia properties as well? Usually they have their own default value, and as for me, just clearing them would be enough.

I would provide the underlaying constructs but not provide the functionality in the Builder. They share the same `Property` type after all.

**Comment by JaggerJo** [comment]
#69

**Comment by Thecentury** [comment]
@JaggerJo, could you please create a new nuget package version with this fix?

**Comment by JaggerJo** [comment]
@Thecentury should be in 0.3.0 (released yesterday). let me know if there are problems
